### ISSUE TITLE
config files

### ISSUE THREAD

**Issue by kvmanohar22** [krssg-ssl/plays.py#8]
@sipah00 Complete [this file](https://github.com/krssg-ssl/plays_py/blob/master/scripts/utils/config.py). Take a look at [this file](https://github.com/krssg-ssl/ssl_common/blob/master/src/config.cpp) for the constants.

**Comment by sipah00** [comment]
@kvmanohar22 Thanks, I am working on this.

**Comment by sipah00** [comment]
@kvmanohar22 ,in [config.cpp](https://github.com/krssg-ssl/ssl_common/blob/master/src/config.cpp) (lines 19 to 21 )ForwardX function-template-- `template<class T> T ForwardX(T distance) {
  return distance;
}` it takes arg as distance and return same thing without doing any thing..so should I make a function in python similar to it ....or give me idea about it.

**Comment by kvmanohar22** [comment]
@sipah00 I don't think we require templates in python. And there is no need to implement `ForwardX()`
